#!/usr/bin/with-contenv sh
exec 2>&1
km apiserver \
  --insecure-bind-address=0.0.0.0 \
  --insecure-port=${K8SM_PORT} \
  --etcd-servers=http://${ETCD_HOST}:${ETCD_PORT} \
  --service-cluster-ip-range=${K8SM_PORTAL} \
  --cloud-provider=mesos \
  --cloud-config=${K8SM_HOME}/mesos-cloud.conf \
  --v=1