#!/usr/bin/with-contenv sh
exec 2>&1
km apiserver \
  --address=${K8SM_IP} \
  --etcd_servers=${ETCD_URL} \
  --portal_net=${K8SM_PORTAL} \
  --port=${K8SM_PORT} \
  --cloud_provider=mesos \
  --cloud_config=${K8SM_CONFIG}