#!/bin/sh

# MESOS_IP - IP that mesos is accessible on
# MESOS_PORT - Port that mesos-master is accessible on (default 5050)
# ETCD_IP - IP that etcd is accessible on
# ETCD_PORT - Port that etcd is accessible on (default 4001)
# LOG_DIR - Directory to write logs to (default /tmp/k8sm-logs)

source /etc/envvars

set -e

export K8SM_HOME=/opt/k8sm
export K8SM_IP=0.0.0.0
export K8SM_PORT=8888

export MESOS_IP=${MESOS_IP:-mesos.service.consul}
export MESOS_PORT=${MESOS_PORT:-5050}
export MESOS_MASTER=${MESOS_IP}:${MESOS_PORT}

export ETCD_IP=${ETCD_IP:-etcd.service.consul}
export ETCD_PORT=${ETCD_PORT:-4001}
export ETCD_URL=http://${ETCD_IP}:${ETCD_PORT}

K8SM_CONFIG="${K8SM_HOME}/mesos-cloud.conf"
if [ ! -f "$K8SM_CONFIG" ]; then
    echo "[mesos-cloud]
        mesos-master        = ${MESOS_MASTER}
        http-client-timeout = 5s
        state-cache-ttl     = 20s
    " > ${K8SM_CONFIG}
fi

LOG_DIR=${LOG_DIR:-"/tmp/k8sm-logs"}
mkdir -p ${LOG_DIR}

export PATH=$PATH:${K8SM_HOME}

export > /etc/envvars