#!/usr/bin/with-contenv sh
exec 2>&1

K8SM_HOST=$(hostname -i)

km scheduler \
  --mesos-master=${MESOS_HOST}:${MESOS_PORT} \
  --address=${K8SM_HOST} \
  --etcd-servers=http://${ETCD_HOST}:${ETCD_PORT} \
  --api-servers=${K8SM_HOST}:${K8SM_PORT}
