#!/bin/bash
# it is not possible to pass environment variables to runit
# so we just save them in a file which we can source from
# run scripts.

export > /etc/envvars

touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

/bin/run-parts --verbose --exit-on-error /etc/runit/1.d