#!/bin/sh
echo "Starting km scheduler"
exec chpst -u nobody km scheduler \
  --mesos_master=${MESOS_MASTER} \
  --address=${K8SM_IP} \
  --etcd_servers=${ETCD_URL} \
  --mesos_user=root \
  --api_servers=${K8SM_IP}:${K8SM_PORT}