#!/usr/bin/with-contenv sh
exec 2>&1

K8SM_HOST=$(hostname -i)

${K8SM_HOME:-/opt/k8sm}/km controller-manager \
  --master=http://${K8SM_HOST}:${K8SM_PORT:-8888} \
  --cloud-provider=mesos \
  --cloud-config=${K8SM_HOME:-/opt/k8sm}/mesos-cloud.conf \
  --v=1
